BEGIN;

ALTER TABLE users
MODIFY COLUMN created_at DATETIME NOT NULL;

ALTER TABLE posts
MODIFY COLUMN created_at DATETIME NOT NULL;

ALTER TABLE reposts
MODIFY COLUMN created_at DATETIME NOT NULL;

COMMIT;
