// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package controller

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Post defines model for Post.
type Post struct {
	Content   *string    `json:"content,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UserId    *string    `json:"user_id,omitempty"`
}

// PostCreate defines model for PostCreate.
type PostCreate struct {
	Content string `json:"content"`
	UserId  string `json:"user_id"`
}

// PostWithReposts defines model for PostWithReposts.
type PostWithReposts struct {
	Post    *Post     `json:"post,omitempty"`
	Reposts *[]Repost `json:"reposts,omitempty"`
}

// Repost defines model for Repost.
type Repost struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	PostId    *string    `json:"post_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UserId    *string    `json:"user_id,omitempty"`
}

// RepostCreate defines model for RepostCreate.
type RepostCreate struct {
	Content string `json:"content"`
	PostId  string `json:"post_id"`
	UserId  string `json:"user_id"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *string    `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Username  *string    `json:"username,omitempty"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostCreate

// PostRepostsJSONRequestBody defines body for PostReposts for application/json ContentType.
type PostRepostsJSONRequestBody = RepostCreate

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a post
	// (POST /posts)
	PostPosts(c *gin.Context)
	// Get a post by ID (include reposts)
	// (GET /posts/{post_id})
	GetPostsPostId(c *gin.Context, postId string)
	// Create a repost
	// (POST /reposts)
	PostReposts(c *gin.Context)
	// Get all users
	// (GET /users)
	GetUsers(c *gin.Context)
	// Create a user
	// (POST /users)
	PostUsers(c *gin.Context)
	// Get all posts for a user
	// (GET /users/{user_id}/posts)
	GetUsersUserIdPosts(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostPosts operation middleware
func (siw *ServerInterfaceWrapper) PostPosts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPosts(c)
}

// GetPostsPostId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPostId(c *gin.Context) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", c.Param("post_id"), &postId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter post_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsPostId(c, postId)
}

// PostReposts operation middleware
func (siw *ServerInterfaceWrapper) PostReposts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostReposts(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// GetUsersUserIdPosts operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdPosts(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdPosts(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/posts", wrapper.PostPosts)
	router.GET(options.BaseURL+"/posts/:post_id", wrapper.GetPostsPostId)
	router.POST(options.BaseURL+"/reposts", wrapper.PostReposts)
	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.GET(options.BaseURL+"/users/:user_id/posts", wrapper.GetUsersUserIdPosts)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xW32vjOBD+V8zcPfTAjdNrH4LferdQAgsbCmUXllBUe9Ko2JZWkruE4P99GUmOndjO",
	"j21a9iV1Jc2M5vu+mdEaEpFLUWBhNMRr0MkSc2Y/Z0Ib+iuVkKgMR7uaiMJgYTfMSiLEoI3ixTNUISQK",
	"mcH0kdnthVA5fUHKDF4aniOEXRuebp0tM572HStlerLrUqN6PMp/tVkRTy+YGLKm9P+3CZ0GwklRFf4o",
	"ucIU4u8bw3Djfj5wra/cLO9RCu04276b9LT9rXABMfwVNQRHnt3IUmvDb5xwg7k+ZOeCQgMXU4qt+vHz",
	"Z7vYvZ9IKODjHysoB8jvSOqkvN4uvzrcfiE+aFTnYRdzxrPexN+Zy4Ll2BO3Gsh2iLrh++8Psou+PVnD",
	"0YWcTHixEOQsRZ0oLg0XBcRwO5sGC6ECcqLDwNZ0GLAiDeoCD8Fwk5G3B4P68ltwO5tCCK+otHNxNRqP",
	"xnRlIbFgkkMM16Px6JrkwMzS5hk1HcdXNqHA6BLTFGLbmmY+HOWG2vwn0tWOupmUGU+sVfSiKXg9dY7p",
	"Wp6Dahs/o0q0C1qKQjtW/h1fnTWyi7kNPK0HXvKWUl3mOVMriMFdNGCWDcKfPWsi2mE4p8MOz2jt662i",
	"WzxjD7B36HCln6mtUKZYjgYVuVwDp7sQTRCCk1urhrdRClsZ7ypy3kFwfFYE22NrCMyFKIs0uPjJzbIW",
	"7z8ky5vxTVf31qIQ3mqHgDs0Hv3gaRVMPwUXvEiyMsXGbz8rraE4rPP7TWG9h9K3RsUHa72e8V2C3M4h",
	"vTv4WtjWeDp0bY/ap/QHe+CNUjzqNWMnWPct08n7M9cmEAvXXvtUlmV+r0na/T/3w7tfQ02m51dQa159",
	"sH4cql0Uaf2Qdgi1HhA3uonW/pVSNbNor47oZ5rWQ+lw22weQR/XNo/S6qz/3T2oVQuPfRR4VPtl2znW",
	"0xLJENVrjVqpMohhaYyMoygTCcuWQpt4MplMgLDw9ru9+kvNjw7YkyjNpmJayGuowoN2dd9tDbqj7Jqn",
	"kLesF6p59SsAAP//i4SLvwYPAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
