// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package controller

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Post defines model for Post.
type Post struct {
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"created_at"`
	Id        string     `json:"id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UserId    string     `json:"user_id"`
}

// PostCreate defines model for PostCreate.
type PostCreate struct {
	Content string `json:"content"`
	UserId  string `json:"user_id"`
}

// PostWithReplies defines model for PostWithReplies.
type PostWithReplies struct {
	Post    Post    `json:"post"`
	Replies []Reply `json:"replies"`
}

// Reply defines model for Reply.
type Reply struct {
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"created_at"`
	Id        string     `json:"id"`
	PostId    string     `json:"post_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	UserId    string     `json:"user_id"`
}

// ReplyCreate defines model for ReplyCreate.
type ReplyCreate struct {
	Content string `json:"content"`
	PostId  string `json:"post_id"`
	UserId  string `json:"user_id"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time  `json:"created_at"`
	Email     string     `json:"email"`
	Id        string     `json:"id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Username  string     `json:"username"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostCreate

// PostRepliesJSONRequestBody defines body for PostReplies for application/json ContentType.
type PostRepliesJSONRequestBody = ReplyCreate

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a post
	// (POST /posts)
	PostPosts(c *gin.Context)
	// Get a post by ID (include replies)
	// (GET /posts/{post_id})
	GetPostsPostId(c *gin.Context, postId string)
	// Create a reply
	// (POST /replies)
	PostReplies(c *gin.Context)
	// Get all users
	// (GET /users)
	GetUsers(c *gin.Context)
	// Create a user
	// (POST /users)
	PostUsers(c *gin.Context)
	// Get all posts for a user
	// (GET /users/{user_id}/posts)
	GetUsersUserIdPosts(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostPosts operation middleware
func (siw *ServerInterfaceWrapper) PostPosts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPosts(c)
}

// GetPostsPostId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPostId(c *gin.Context) {

	var err error

	// ------------- Path parameter "post_id" -------------
	var postId string

	err = runtime.BindStyledParameterWithOptions("simple", "post_id", c.Param("post_id"), &postId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter post_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsPostId(c, postId)
}

// PostReplies operation middleware
func (siw *ServerInterfaceWrapper) PostReplies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostReplies(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// GetUsersUserIdPosts operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserIdPosts(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", c.Param("user_id"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserIdPosts(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/posts", wrapper.PostPosts)
	router.GET(options.BaseURL+"/posts/:post_id", wrapper.GetPostsPostId)
	router.POST(options.BaseURL+"/replies", wrapper.PostReplies)
	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.GET(options.BaseURL+"/users/:user_id/posts", wrapper.GetUsersUserIdPosts)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXb2vbPhD+KuJ+vxcduHG69kXwu26DEhgsFMoGIxTVvjQqtqVJckcI/u7jZDlxYqVJ",
	"+o/tTZpKd6fnnnt0pywhlYWSJZbWQLIEk86x4O7rRBpLf5WWCrUV6FZTWVos3YZdKIQEjNWivIc6glQj",
	"t5jdcrc9k7qgb5Bxi6dWFAhR30dkG7ZVLrKQWaWyo0NXBvXtQfHrCDT+qoTGDJKf4Exa72iV8kaC01UQ",
	"efeAqaUDibHPzuQ43p4NtI9xF6zvws6vUeUezSY25Sv9v8YZJPBfvNZE7AUROzW441dBhMXC7POjQxfk",
	"6GFxrfmil4hDsA4eyqIJ9LfokQDf/gPabXEeoWJH9HNkfBQnL5d8P7VQNjcGdSCNZygDCy7yYOJvrIOS",
	"Fxg4d1fhnXkLd2+1iZ9dxd6d8eGweoj6IMhFlDNJwTI0qRbKCllCApeTMZtJzSiIiRhV3ESMlxlrO0UE",
	"Vticot1YNKc/2OVkDBE8ojZNiLPBcDAkyFJhyZWABM4Hw8E5CYjbucszdoG7nZBY4ARinEHiGujEmTS5",
	"obGfZLbYug9cqVykzit+MHR4O04P6a2+BvUmf1ZX6BaMkqVpqvJxePaqJzdnbhJP68wrx5XUVEXB9QIS",
	"aIAyznzPtvzetC3cwJSMGz7jpb+hNaG4xwCxV9jwSh9jd6e55gVa1BRyCYKwUJkggkZunVu/yVLUyXhb",
	"kdMeg8NXZbA7XHeROZNVmbGT38LOW/F+IFleDC/6uncepfReWwW4QuvZZ3cLNv7CTkSZ5lWG67jhqnRG",
	"926dX68u1lsovTtb3lnq/iHSL4/b2Cd27bzDvLru9JTGb5zBC0V40GvLTbv+Y6uX81dhLJOzprGG9JXn",
	"fm+dcvP/1A/6sHrWmb6+djqT6p2l07DaZ5HW9wmHWAuQuNJNvPQvmno9hZ7UEX2Ms3Yc7W+Y6wfT+zXM",
	"g7Ta/qI4VKuOHvcc8KyGZdszC1xackT92LJW6RwSmFurkjjOZcrzuTQ2GY1GIyAuvP92l/7W1scwficr",
	"u7oxHeYN1NFeP+WL2RlxBupp/ScAAP//nChwEJ0PAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
