// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	Posts            string
	Replies          string
	SchemaMigrations string
	Users            string
}{
	Posts:            "posts",
	Replies:          "replies",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
